"""
config_reader.py
----------------
Reads the human-provided Excel configuration file that accompanies
a PDF when the automatic section detection is insufficient.

The Excel file has a simple two-column structure:
  Column A: field name (label)
  Column B: value

Expected fields (case-insensitive, accent-insensitive):
  - "Page début"         : first page of the materials section (integer)
  - "Page fin"           : last page of the materials section (integer)
  - "Colonnes à extraire": comma-separated list of column names to extract
                           exactly as they appear in the source document

Example Excel content:
  Page début            | 8
  Page fin              | 15
  Colonnes à extraire   | Localisation, Résultat, Référence échantillon, MRS

Usage
-----
    from app.documents.parsers.config_reader import ConfigReader

    config = ConfigReader().read("config.xlsx")
    # Returns:
    # {
    #     "page_start": 8,
    #     "page_end": 15,
    #     "columns_to_extract": ["Localisation", "Résultat", "Référence échantillon", "MRS"]
    # }
    # Missing fields default to None — caller decides how to handle them.

File location in project
-------------------------
    backend/app/documents/parsers/config_reader.py

The Excel template for the team is generated by ConfigReader.generate_template().
"""

import unicodedata
from pathlib import Path

import openpyxl


# ---------------------------------------------------------------------------
# Label vocabulary — normalised keys that map to our internal field names.
# Add synonyms here if teams use different labels.
# ---------------------------------------------------------------------------
_LABEL_MAP = {
    # page_start
    "page debut":          "page_start",
    "page de debut":       "page_start",
    "debut":               "page_start",
    "page start":          "page_start",
    "premiere page":       "page_start",
    # page_end
    "page fin":            "page_end",
    "page de fin":         "page_end",
    "fin":                 "page_end",
    "page end":            "page_end",
    "derniere page":       "page_end",
    # columns_to_extract
    "colonnes a extraire": "columns_to_extract",
    "colonnes":            "columns_to_extract",
    "champs a extraire":   "columns_to_extract",
    "columns to extract":  "columns_to_extract",
    "columns":             "columns_to_extract",
}


def _normalize(text: str) -> str:
    """Lowercase + strip accents for fuzzy label matching."""
    nfkd = unicodedata.normalize("NFKD", str(text).lower().strip())
    return "".join(c for c in nfkd if not unicodedata.combining(c))


class ConfigReader:
    """
    Reads a two-column Excel file and returns a structured config dict.
    Tolerant of extra whitespace, accent variations, and unknown rows.
    """

    def read(self, file_path: str | Path) -> dict:
        """
        Parameters
        ----------
        file_path : str or Path
            Path to the .xlsx config file provided by the user.

        Returns
        -------
        dict with keys:
            page_start          : int | None
            page_end            : int | None
            columns_to_extract  : list[str] | None
        """
        file_path = Path(file_path)
        if not file_path.exists():
            raise FileNotFoundError(f"Config file not found: {file_path}")

        if file_path.suffix.lower() not in (".xlsx", ".xls"):
            raise ValueError(
                f"Config file must be .xlsx or .xls, got: {file_path.suffix}"
            )

        wb = openpyxl.load_workbook(file_path, data_only=True)
        ws = wb.active  # always use the first sheet

        raw: dict[str, str] = {}

        for row in ws.iter_rows(min_col=1, max_col=2, values_only=True):
            label_cell, value_cell = row

            if label_cell is None:
                continue

            normalized_label = _normalize(str(label_cell))
            internal_key = _LABEL_MAP.get(normalized_label)

            if internal_key is None:
                continue  # Unknown label — skip silently

            raw[internal_key] = str(value_cell).strip() if value_cell is not None else ""

        return self._build_config(raw)

    def _build_config(self, raw: dict[str, str]) -> dict:
        """
        Converts raw string values into typed Python objects.
        Returns None for any field that was absent or unparseable.
        """
        config = {
            "page_start":         None,
            "page_end":           None,
            "columns_to_extract": None,
        }

        # ── page_start ────────────────────────────────────────────────────
        if "page_start" in raw:
            try:
                val = int(float(raw["page_start"]))
                if val >= 1:
                    config["page_start"] = val
                else:
                    print(f"[ConfigReader] Warning: page_start={val} is < 1, ignored")
            except (ValueError, TypeError):
                print(f"[ConfigReader] Warning: could not parse page_start={raw['page_start']!r}")

        # ── page_end ──────────────────────────────────────────────────────
        if "page_end" in raw:
            try:
                val = int(float(raw["page_end"]))
                if val >= 1:
                    config["page_end"] = val
                else:
                    print(f"[ConfigReader] Warning: page_end={val} is < 1, ignored")
            except (ValueError, TypeError):
                print(f"[ConfigReader] Warning: could not parse page_end={raw['page_end']!r}")

        # ── Sanity check: start must be <= end ────────────────────────────
        if (
            config["page_start"] is not None
            and config["page_end"] is not None
            and config["page_start"] > config["page_end"]
        ):
            print(
                f"[ConfigReader] Warning: page_start ({config['page_start']}) "
                f"> page_end ({config['page_end']}) — both ignored"
            )
            config["page_start"] = None
            config["page_end"]   = None

        # ── columns_to_extract ────────────────────────────────────────────
        if "columns_to_extract" in raw and raw["columns_to_extract"]:
            cols = [
                c.strip()
                for c in raw["columns_to_extract"].split(",")
                if c.strip()
            ]
            if cols:
                config["columns_to_extract"] = cols

        return config

    # ------------------------------------------------------------------
    # Template generator
    # ------------------------------------------------------------------

    @staticmethod
    def generate_template(output_path: str | Path = "config_template.xlsx") -> Path:
        """
        Generates the Excel template file that the team fills in and uploads.

        Call this once to produce the template:
            ConfigReader.generate_template("config_template.xlsx")
        """
        output_path = Path(output_path)
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Configuration"

        from openpyxl.styles import Font, PatternFill, Alignment

        header_font = Font(bold=True, color="FFFFFF", name="Arial", size=11)
        header_fill = PatternFill("solid", fgColor="1F4E79")
        label_font  = Font(bold=True, name="Arial", size=10)
        value_font  = Font(name="Arial", size=10)
        note_font   = Font(italic=True, color="888888", name="Arial", size=9)
        center      = Alignment(horizontal="center", vertical="center")
        left        = Alignment(horizontal="left", vertical="center", wrap_text=True)

        ws.append(["Champ", "Valeur", "Description"])
        for col in range(1, 4):
            cell = ws.cell(row=1, column=col)
            cell.font      = header_font
            cell.fill      = header_fill
            cell.alignment = center

        rows = [
            (
                "Page début",
                "",
                "Numéro de la première page contenant les matériaux (ex: 8)",
            ),
            (
                "Page fin",
                "",
                "Numéro de la dernière page contenant les matériaux (ex: 15)",
            ),
            (
                "Colonnes à extraire",
                "",
                "Noms exacts des colonnes à extraire, séparés par des virgules "
                "(ex: Localisation, Résultat, Référence échantillon, MRS)",
            ),
        ]

        for i, (label, value, description) in enumerate(rows, start=2):
            ws.cell(row=i, column=1, value=label).font = label_font
            ws.cell(row=i, column=1).alignment         = left
            ws.cell(row=i, column=2, value=value).font = value_font
            ws.cell(row=i, column=2).alignment         = left
            ws.cell(row=i, column=3, value=description).font = note_font
            ws.cell(row=i, column=3).alignment              = left

            if i % 2 == 0:
                fill = PatternFill("solid", fgColor="F2F7FC")
                for col in range(1, 4):
                    ws.cell(row=i, column=col).fill = fill

        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 40
        ws.column_dimensions["C"].width = 55
        ws.row_dimensions[1].height     = 20

        wb.save(output_path)
        return output_path